#!/usr/bin/env python3

import compress
import glob
import difflib

modules = [
        #compress.abb016,
        compress.che171,
        compress.chu077,
        compress.li0003,
        compress.lin033,
        compress.mor018,
        compress.san020,
        compress.tak006,
        #compress.yan031,
        compress.tands,
]


for path in sorted(glob.glob('texts/*.txt')):
    print(path)
    for mod in modules:
        with open(path) as f:
            text1 = f.read()

        data = ''
        compress_error = None
        try:
            data = mod.compress(text1)
        except Exception as ex:
            data = ''
            compress_error = ex

        text2 = ''
        decompress_error = None
        try:
            text2 = mod.decompress(data)
        except Exception as ex:
            decompress_error = ex
            text2 = ''

        sm = difflib.SequenceMatcher(None, text1, text2)
        compression_ratio = 100 * len(data) / len(text1)
        loss_ratio = 100 * sm.ratio()

        print(
                '  '
                f'{mod.__name__:20s}   '
                f'{compression_ratio:4.1f}%   '
                f'{loss_ratio:4.1f}%', end=' ')

        if len(text1) < 20:
            print(repr(text1), repr(text2))
        else:
            print('')
